### PR TITLE
add back the git branch fetching

### PR DESCRIPTION
**Pull request by EndangeredMassa**
2.0.0 is currently broken. This probably fixes it, but I can't test it right now.

I'll work on a test suite after the refactor gets in.

---

Addresses: https://github.com/EndangeredMassa/npub/issues/34

### CODE REVIEW

**Comment by jkrems** [comment]
LGTM

**Comment by khoomeister** [comment]
Hey @EndangeredMassa, when will this be released?

**Comment by EndangeredMassa** [comment]
I've been out, but now I'm back. I'll get a release out today after I test this.

**Comment by EndangeredMassa** [comment]
tested and it seems to work fine

**Comment by EndangeredMassa** [comment]
published in [2.0.1](https://github.com/EndangeredMassa/npub/releases/tag/v2.0.1)

**Pull request merged**
